import * as parafin from './parafin'
import { ParafinError } from './parafin'
import { Err, Ok, PartnerResponse } from './types'

const token =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlVzdGF4a2RCWVlJUTc3dnV4TlE1WSJ9.eyJodHRwczovL2FwaS5kZXYucGFyYWZpbi5jb20vdXNlcl9hdXRob3JpemF0aW9uIjp7ImFwcF9tZXRhZGF0YSI6eyJ1c2VySWQiOiJkZWIwYjQ3MS05MGRhLTQwYjgtOTBjMS03MGIzZTVjYjIyMDEifX0sIm5pY2tuYW1lIjoibWluZGJvZHkrZGViMGI0NzEtOTBkYS00MGI4LTkwYzEtNzBiM2U1Y2IyMjAxIiwibmFtZSI6Im1pbmRib2R5K2RlYjBiNDcxLTkwZGEtNDBiOC05MGMxLTcwYjNlNWNiMjIwMUBwYXJhZmluLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci82ZjM1ZGEyNDJjMjAyYTM0OGQzZTFkMmQ3NDQ5YzQyYj9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRm1pLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIxLTA5LTE0VDAwOjMwOjQ2LjY4N1oiLCJlbWFpbCI6Im1pbmRib2R5K2RlYjBiNDcxLTkwZGEtNDBiOC05MGMxLTcwYjNlNWNiMjIwMUBwYXJhZmluLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2xvZ2luLmRldi5wYXJhZmluLmNvbS8iLCJzdWIiOiJhdXRoMHw2MTA4OGExNzJkYTFhMDAwNzE2OGY4Y2YiLCJhdWQiOiI5bDJraGpOODJPdkExWVl3NUJNZHp4eWtqY2lqNEhOcyIsImlhdCI6MTYzMTU3OTQ0NiwiZXhwIjoxNjMxNjE1NDQ2fQ.R05vFBYF8qHT9W9HZc1IPwDLe0Sj1LGOfKAfcOLfwYc70AHcjvjsS0HiwEg44kRDPexut04bUU6xRGkrAqzTiodHhbJSD2NdNORqlwfFa_zl0FgYq4IYt2bCOsB4dkur9WFpbly_jXd4XQ180248F2L6uIoSKfalPQoLouoYnQhqr2mO8FD-q106vnX2t6Z6yEWL2DhEcz44g2vczbGqgfKV4oBNj4s-BZBN0uXrlByvtE9HhsXHEiw4Vi6gc9Fi1wb2t12F7gwTj1lNamiNMbmBW4jflI3J0yjxqEPQqNmNdZ4XPWzLtUiRokaKY77eIUNK7LteWdLKFkMg8mZuRw'
const parafinClient = new parafin.Client({
  token: token,
  environment: parafin.environment.development
})

parafinClient
  .partners()
  .then((res: Ok<PartnerResponse, ParafinError>) => {
    const popo: PartnerResponse = res.value
    console.log(popo)
  })
  .catch((res: Err<PartnerResponse, ParafinError>) => {
    const erro: ParafinError = res.error
    console.log(erro)
  })
