name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - review_requested

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm run build
      - run: npm run lint
