name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node 12 and .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Update version
      - run: npm version patch

      - name: Publish
      - run: npm publish
          env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
